### PR TITLE
Start profiling via func call

### PR DESCRIPTION
**Pull request by plutov**
Sometimes it's good to start profiling automatically. For example, I configured my app to start it only if I started service with "-p=localhost:6060". So if I am sure I can start it automatically.

### CODE REVIEW

**Comment by wblakecaldwell** [comment]
Thanks for the contribution!

I like the changes. Bear with me - I'm still relatively new to the receiving end of pull requests, so I'm going to tinker with the workflow.

**Comment by wblakecaldwell** [comment]
I'd like to accept this, but as just one commit. Could you squash and resubmit? If not, I'd be glad to do it for you, but if I did, I don't think you'd show up in the commit history, and I'd like to have you listed as a contributor.

Thanks!

**Comment by plutov** [comment]
Sure, please check

**Comment by wblakecaldwell** [comment]
Merged - thanks again!

**Comment by wblakecaldwell** [comment]
Grr... I don't know why, but GitHub didn't preserve a link to your account in the commit history. I even automatically merged right from here.

**Comment by plutov** [comment]
I got it, I did push from my working PC, where git is configured with another email. I will do one more PR in future.

**Comment by wblakecaldwell** [comment]
deal!

**Pull request merged**
